# Generated by Django 4.2.2 on 2023-06-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calories", "0002_alter_calories_calories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calories",
            name="calories",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
