# Generated by Django 4.2.2 on 2023-06-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="calories_per_day",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
